### PR TITLE
EpiAware Problem object

### LINKED ISSUE #145: Problem object

### PR DESCRIPTION
**Pull request by SamuelBrand1**
As discussed in #122, we want an `EpiAwareProblem` struct which defines the inference and/or generative modelling problem implied by case data and the choices in the underlying epi modelling.

Where I'm lacking a bit of clarity is where we include observed case data. At the moment, we are passing case data to a Turing model which implements the observation model behaviour. If we want to go on with this then case data should be a field of `EpiAwareProblem`. 

However, the alternative as discussed in #119 is to have observed case data as an intrinsic part of the Observation model through conditioning. In that case, this PR is nearly done already (but we'll need a bit more engineering on the observation model).

TBD:

- [x] Some testing for `EpiAwareProblem`.
- [x] ~~Add observational data field if we want to go that way.~~

Closes #145

### CODE REVIEW

**Review by seabbs — COMMENTED** [review]
Yes this is nice and I think I agree that we want to use conditioning and so don't need to carry around the observed data.

The only thing I might need clarity on is what we are conditioning on. Is it the output of `make_epi_aware` or of the observation submodule?

**Comment by SamuelBrand1** [comment]
> The only thing I might need clarity on is what we are conditioning on. Is it the output of `make_epi_aware` or of the observation submodule?

Either works, but my leaning is towards conditioning on the observation part and supplying the conditioned observation model to `EpiAwareProblem`.

The reason I lean that way is because that can have utility in isolation:
- We can test/check the `logpdf` of the conditioned observation model for any supplied array of unobserved infections.
- We can test/check partially missing data support rather than in the the full `make_epi_aware` output.

**Comment by seabbs** [comment]
> The reason I lean that way is because that can have utility in isolation:

Can't we always condition on the lower levels modules whenever we want and so either approach would allow you to do this? The thing you lose I think is that you can't updating the conditioning on `make_epi_aware` and so need to respecify the problem w/ new data? 

> I envision this as the next step; this PR is just adding the EpiAwareProblem struct which is compatible with either approach.

That sounds sensible

**Comment by seabbs** [comment]
Is this ready for a review?

**Comment by SamuelBrand1** [comment]
> Can't we always condition on the lower levels modules whenever we want and so either approach would allow you to do this? The thing you lose I think is that you can't updating the conditioning on `make_epi_aware` and so need to respecify the problem w/ new data?

Yeah, thats a reasonable point.

**Comment by seabbs** [comment]
The test failure looks like a stochastic issue with pathfinder maybe indicating those tests are a bit loose. Will kick it off again

**Comment by SamuelBrand1** [comment]
> The test failure looks like a stochastic issue with pathfinder maybe indicating those tests are a bit loose. Will kick it off again

Yes. I tracked it down to

```julia
@model function bad_model()
            x ~ Normal(0, 1)
            return sqrt(x) #<-fails
        end
```

It supposed to not be able to optimize for that model!

**Review by seabbs — APPROVED** [review]
This looks good to me.

**Comment by SamuelBrand1** [comment]
Ok now the merged in test failed.

> Testing DiffLatentModel process: Test Failed at /Users/runner/work/Rt-without-renewal/Rt-without-renewal/test/test_difflatentmodel.jl:67
  Expression: ks_test_pval_day2 > 1.0e-6
   Evaluated: 4.604227577138768e-8 > 1.0e-6

**Comment by seabbs** [comment]
I've kicked them off again. 

Regarding the test failure - shall we resolve in a new issue?

**Comment by SamuelBrand1** [comment]
> I've kicked them off again.
> 
> Regarding the test failure - shall we resolve in a new issue?

The test failure is because the test is broken.

The problem here is that a two fold `cumsum` on the random vector 

```math
X = [X_1, X_2] \to_{\Delta^{(-2)}} [X_1,  X_2 + 2 X_1]
```

But our test is treating it as 

```math
[X_1,  X_2 +  X_1 + \tilde{X}_1]
```

Where $\tilde{X}_1$ is an independent copy of $X_1$. The distribution is wrong, so the test was failing as it should.

**Pull request merged**
