### PR TITLE
Replace cumsum broadcast with accumulate

### PR DESCRIPTION
**Pull request by seabbs**
Tests a single change from #470

### CODE REVIEW

**Comment by seabbs** [comment]
So this has a different pattern of impact vs #470. 

Here I see slower evaluation and forward diff, no real impact on reversediff with compilation and much faster reverse diff. 

Is this due to a specialisation that exists for `accumulate` do we think or other? 

I think this one is worth changing given these results (this makes me want to get Enzyme and Tapir into the benchmarks asap)

**Comment by SamuelBrand1** [comment]
> Is this due to a specialisation that exists for `accumulate` do we think or other?

This is possible, but `cumsum` calls down to `accumulate!` which I'd imagine has similar things happening.

My mental model _was_ that `accumulate` saves either a broadcast sum or a vcat by using the `init` keyword arg... but I'm not sure thats the win I thought it would be now.

**Comment by SamuelBrand1** [comment]
I've refreshed this test with the `xexpy` based function committed on main by #473

**Comment by SamuelBrand1** [comment]
This is still ambiguous: some cases worse, some better.

As per f2f discussion with @seabbs I think that mean not going forward with this unless we get extra evidence. For example, if in a realistic inference exercise some kind of extra sampling stability improves sampling overall even if individual primal+grad calls are slower.

**Pull request closed without merging**
