### PR TITLE
Fix the replication note and turn it into a full replication

### LINKED ISSUE #435: Bug: Mishra et al replication error
Unfortunately, our replication of Mishra et al has failed silently. 

From local experimentation, the chance of the sampler getting stuck in a poor part of parameter regime is removed by increasing the `nadapts` steps in warm-up along with a higher target acceptance rate.

### PR DESCRIPTION
**Pull request by SamuelBrand1**
This PR builds on #441 as well as rewriting the Mishra et al replication note to fully replicate that pre-print.

In doing this I think it became clear that the structure of the model makes it hard to identify the AR process std parameter (the other parameters have strong priors) from the neg bin observation cluster factor. In the preprint no prior for neg bin was found (apols if I missed it!). Therefore, I demonstrated conditioning the value and running the inference on the model with conditioned cluster factor.

Closes #435 and #420.

### CODE REVIEW

**Review by seabbs — COMMENTED** [review]
I really like this rewrite. I am not clear why it needed to be built on top of #441 though?

**Comment by SamuelBrand1** [comment]
> I really like this rewrite. I am not clear why it needed to be built on top of #441 though?

We had strong priors on the AR parameters in the wrong order (which strongly effects the prior variance of the process etc). Obviously, I could have just swapped them (as well as the other changes) but that felt silly because we'd have just had to swap back after #441.

**Comment by seabbs** [comment]
I'm still a bit uncomfortable about #441. I know its annoying but any chance we can decouple?

**Comment by SamuelBrand1** [comment]
> I'm still a bit uncomfortable about #441. I know its annoying but any chance we can decouple?

Yeah, sure. Probably easiest to wait until we've decided what we want with `AR` then merge that into this?

**Comment by SamuelBrand1** [comment]
Ok, I `git reset` the commits, reversed the notebook `damp_prior` vector for correctness and force pushed that back.

**Comment by seabbs** [comment]
ty - sorry for being a pain

**Review by seabbs — APPROVED** [review]

**Review by seabbs — DISMISSED** [review]

**Review by seabbs — APPROVED** [review]

**Pull request merged**
