### PR TITLE
Fix benchmark ci

### PR DESCRIPTION
**Pull request by SamuelBrand1**
This PR hotfixes `BenchmarkCI.jl` incompat by creating a local version with appropriate compatibility.

This should only be seen as temporary until https://github.com/tkf/BenchmarkCI.jl/pull/181 is resolved

### CODE REVIEW

**Comment by SamuelBrand1** [comment]
Making `BenchmarkCI` a local resources seems to make it hard to run `PkgBenchmark`. Not really sure whats causing the problem with reading the generated `Manifest`

**Review by seabbs — APPROVED** [review]

**Comment by seabbs** [comment]
This looks like its still having some problems?

**Comment by seabbs** [comment]
@SamuelBrand1 problems here?

**Comment by SamuelBrand1** [comment]
Yes, I'm really not understanding the error here. Because `PkgBenchmark` _is_ registered.

**Comment by seabbs** [comment]
I think we want to rebase this off main vs trying to stack it in the ode process pr

**Comment by SamuelBrand1** [comment]
> I think we want to rebase this off main vs trying to stack it in the ode process pr

Shall I close this, and we can revisit?

**Pull request closed without merging**
