### PR TITLE
change exp to xexpy

### LINKED ISSUE #469: Change calculation method in `EpiAwareBase.generate_latent_infs(epi_model::ExpGrowthRate, rt)`

### PR DESCRIPTION
**Pull request by SamuelBrand1**
This is a small PR to replace the calculation of `ExpGrowthRate` infection generating process with `LogExpFunctions.xexpy` to get their overflow properties. 

The reason I targeted this specific bit of the code base it that everywhere else we can define `transformation` whereas here the `exp` transform is baked into the meaning of the igp.

Closes #469 .

NB: I also changed from `cumsum` to `accumulate(+, rt; init = init_incidence)` to avoid a broadcast add before applying the "safe" `xexpy`. I wonder if anything shows in benchmarks.

### CODE REVIEW

**Review by seabbs — APPROVED** [review]
Nice. Agree we should hold off merging until we see what happens in the benchmarks

**Comment by SamuelBrand1** [comment]
updated a hotfix for the doc fix

**Comment by SamuelBrand1** [comment]
> ID | time ratio | memory ratio
-- | -- | --
["EpiInfModels", "ExpGrowthRate", "evaluation", "linked"] | 1.13 (5%) ❌ | 1.06 (1%) ❌
["EpiInfModels", "ExpGrowthRate", "evaluation", "standard"] | 1.13 (5%) ❌ | 1.06 (1%) ❌
["EpiInfModels", "ExpGrowthRate", "gradient", "ADTypes.AutoForwardDiff(chunksize=0)", "linked"] | 1.09 (5%) ❌ | 1.12 (1%) ❌
["EpiInfModels", "ExpGrowthRate", "gradient", "ADTypes.AutoForwardDiff(chunksize=0)", "standard"] | 1.10 (5%) ❌ | 1.12 (1%) ❌
["EpiInfModels", "ExpGrowthRate", "gradient", "ADTypes.AutoReverseDiff()", "linked"] | 0.43 (5%) ✅ | 0.79 (1%) ✅
["EpiInfModels", "ExpGrowthRate", "gradient", "ADTypes.AutoReverseDiff()", "standard"] | 0.43 (5%) ✅ | 0.79 (1%) ✅
["EpiInfModels", "ExpGrowthRate", "gradient", "ADTypes.AutoReverseDiff(compile=true)", "linked"] | 1.19 (5%) ❌ | 0.35 (1%) ✅
["EpiInfModels", "ExpGrowthRate", "gradient", "ADTypes.AutoReverseDiff(compile=true)", "standard"] | 1.18 (5%) ❌ | 0.35 (1%) ✅

Seems the relevant bit of the benchmarking? I think thats overall bad? But very big performance gain with not compiled tape AD?

**Comment by seabbs** [comment]
Yes agree. I think ideally we would look at: 

1. xexpy in isolation
2. Doing cumsum(preprend etc in isolation)

**Comment by SamuelBrand1** [comment]
> Yes agree. I think ideally we would look at:
> 
> 1. xexpy in isolation
> 2. Doing cumsum(preprend etc in isolation)

Good thinking and I've noted #472

**Comment by seabbs** [comment]
So the `expy` change appears to have little impact on current benchmarks for forward diff. Making things significantly faster on reverse diff but hurt when using compiled reverse diff. 

So quite a mixed bag. I don't have a strong mental model to explain that result

**Comment by SamuelBrand1** [comment]
> So the `expy` change appears to have little impact on current benchmarks for forward diff. Making things significantly faster on reverse diff but hurt when using compiled reverse diff.
> 
> So quite a mixed bag. I don't have a strong mental model to explain that result

Me neither.

**Pull request closed without merging**
