### PR TITLE
Issue 58: Add new GitHub Actions

### LINKED ISSUE #58: Setup suggest Julia actions
Setup suggested Julia actions using `julia-actions`

### PR DESCRIPTION
**Pull request by seabbs**
This PR closes #58 by adding a range of GitHub Actions. Note that until all actions are passing it is not likely worht reviewing.

### CODE REVIEW

**Review by seabbs — COMMENTED** [review]
Note it also moves us to use the `sciml` style for `JuliaFormatter` and runs this everywhere.

**Review by seabbs — COMMENTED** [review]
Note it also moves us to use the `sciml` style for `JuliaFormatter` and runs this everywhere.

**Comment by SamuelBrand1** [comment]
LGTM!

**Comment by seabbs** [comment]
Note I am not 100% that coverage will work properly because of the workarounds I've had to put in place to get this all working in a monorepo. 

This might be starting to indicate that we want to move to a multi-repo structure but we can discuss that down the line I think

**Review by SamuelBrand1 — APPROVED** [review]

**Pull request merged**
