### PR TITLE
EpiAware specific predict method to handle prediction edge cases

### PR DESCRIPTION
**Pull request by seabbs**
This PR was spun out of #369 and implements a custom predict method and predict context. See that PR for discussion

### CODE REVIEW

**Comment by seabbs** [comment]
I'm still stuck on this but tempted to pause work on it as the fix in `Turing` seems to be gaining traction (https://github.com/TuringLang/Turing.jl/issues/2239)

**Comment by SamuelBrand1** [comment]
> I'm still stuck on this but tempted to pause work on it as the fix in `Turing` seems to be gaining traction ([TuringLang/Turing.jl#2239](https://github.com/TuringLang/Turing.jl/issues/2239)) and so maybe we can just wait on that.

I think thats a good idea.

**Comment by seabbs** [comment]
It seems like progress on this on the Turing side might be quite slow so we might need to implement something here sooner rather than later.

**Comment by SamuelBrand1** [comment]
How is this going?

**Comment by seabbs** [comment]
it was passed to wait for Turing. Do you think we need it soon?

**Pull request closed without merging**
