### PR TITLE
New figure 1 function

### LINKED ISSUE #374: Modify Fig1 to split between main and SI figs

### PR DESCRIPTION
**Pull request by SamuelBrand1**
This is a small PR which modifies the figure 1 generation to meet discussion points in #370 (and elsewhere). The new generation script generates a figure for each latent model choice (one to be used in main ms and others for SI).

Close #374

### CODE REVIEW

**Review by seabbs — DISMISSED** [review]
Nice looks good. I am a bit surprised you've needed to make subplots and compose vs using `AlgebraofGraphics` facet mechanics (which is what I would do if making this in `ggplot2` for example. 

What do you think about moving the legend to below the plot vs on the side?

**Comment by SamuelBrand1** [comment]
> Nice looks good. I am a bit surprised you've needed to make subplots and compose vs using `AlgebraofGraphics` facet mechanics (which is what I would do if making this in `ggplot2` for example.

My problem here was that I/search engines couldn't work out how to vary the ylims figure by figure... I'm being a bit basic here I think. I agree because unlike the first pass fig 1 now the subplots are slightly different sized.

**Comment by SamuelBrand1** [comment]
I forgot the reference date indication (mentioned by @seabbs f2f)! Added now.

This now closes #377

**Comment by seabbs** [comment]
Can you do it by specifying it as a variable in the data? I think that would be the ggplot2 solution?

**Review by seabbs — APPROVED** [review]

**Pull request merged**
