### PR TITLE
issue 492: Create distribution that returns `<: Union{Int,BigInt}`

### PR DESCRIPTION
**Pull request by SamuelBrand1**
~This draft PR is as per #494 except that I've sharpened the rand return value from `Real` to `Union{Int,BigInt}`~

This PR closes #494 

The contributions are:
1. Creating an alias `SafeInt` for `Union{Int,BigInt}`.
2. Creating a custom subtype of `Distributions.ValueSupport` called `SafeIntValued`.
3. Created a custom `Distribution` subtype `Distribution{Univariate, SafeIntValued}` with alias `SafeDiscreteUnivariateDistribution`
4. `SafeDiscreteUnivariateDistribution` has an `eltype` method that dispatches on this so that `rand` calls on `SafeDiscreteUnivariateDistribution` objects such as our `SafePoisson` and `SafeNegativeBinomial` types are expecting `SafeInt` returns.

### CODE REVIEW

**Comment by SamuelBrand1** [comment]
This is ready for review. Things to note:

- I am interpreting the benchmarking positively. The most impacted by this change: `["EpiObsModels", "NegativeBinomialError", "gradient", "ADTypes.AutoReverseDiff(compile=true)", "linked"]` has has a decent improvement.
- This branch has not had #491 merged, but has _also_ resolved #490

**Comment by seabbs** [comment]
Agree this looks like it improves average performance which is great. Should we revert #490 here to show it fixes the problem and because that was only ever a hotfix?

**Review by seabbs — DISMISSED** [review]
This is great but its kind of mad we have to do it! As I said I think we should revert the test hotfix here before merging.

**Comment by SamuelBrand1** [comment]
> This is great but its kind of mad we have to do it! As I said I think we should revert the test hotfix here before merging.

Lets do it.

Even more context: the test branch with `Real` can run all the prior predictive checks but fails various parameter recovery tests but this branch still needs restrained priors (e.g. no sampling for `1e67` infections).

**Comment by SamuelBrand1** [comment]
I caught a typo and a non-use of the `SafeInt` alias

**Review by seabbs — DISMISSED** [review]

**Comment by seabbs** [comment]
I see a test failure now (also noting we have a noisy sampling step again in our tests)

**Comment by SamuelBrand1** [comment]
> I see a test failure now (also noting we have a noisy sampling step again in our tests)

Yes just saw. Hmmm

**Comment by SamuelBrand1** [comment]
Hmmm seems to be a `Ubuntu` problem. Not sure why.

**Comment by seabbs** [comment]
Here right: 

    LatentDelay parameter recovery with mix of IGP + latent processes: Negative binomial errors + EpiProblem interface                                                                                                                                                                                                                                                                                                                                                 |   29     1     30  40m09.0s
      Check true parameters are within 99% central post. prob.:                                                                                                                                                                                                                                                                                                                                                                                                        |   29     1     30  40m04.2s

(and is it really taking 40 minutes to run!)

**Comment by seabbs** [comment]
If yes it is the section of code that had the hotfix: https://github.com/CDCgov/Rt-without-renewal/blob/dfe658a0260241768f1259958e814f0e54a6d264/EpiAware/test/EpiObsModels/modifiers/LatentDelay.jl#L177

So perhaps revert that and see?

**Comment by SamuelBrand1** [comment]
> Here right:
> 
> ```
> LatentDelay parameter recovery with mix of IGP + latent processes: Negative binomial errors + EpiProblem interface                                                                                                                                                                                                                                                                                                                                                 |   29     1     30  40m09.0s
>   Check true parameters are within 99% central post. prob.:                                                                                                                                                                                                                                                                                                                                                                                                        |   29     1     30  40m04.2s
> ```
> 
> (and is it really taking 40 minutes to run!)

Yeah its a matrix of full inference checks, its been about 40 mins since we committed it.

**Comment by seabbs** [comment]
where are we with this? Did you try adding back in the test hot fix so we can merge this?

**Comment by SamuelBrand1** [comment]
> where are we with this? Did you try adding back in the test hot fix so we can merge this?

Yes in another branch but that failed. I'm investigating.

**Comment by seabbs** [comment]
Plan is to check it again with the hotfix readded and explore that in its own PR

**Comment by seabbs** [comment]
I think still waiting for the hotfix to go back in

**Comment by SamuelBrand1** [comment]
> I think still waiting for the hotfix to go back in

We are currently tweaking this on #503 .

**Review by seabbs — APPROVED** [review]
This looks good to me now. I interpret benchmarks as indicating a small speed up in some settings with little clear evidence of a downside

**Comment by seabbs** [comment]
🥳

**Pull request merged**
