### PR TITLE
Write and test a forecast function which projects inference forwards in time

### LINKED ISSUE #231: Write and test a forecast function which projects inference forwards in time.

### PR DESCRIPTION
**Pull request by SamuelBrand1**
This PR implements a forecasting function for the pipeline. The idea behind this function is to use `Turing.predict` to sample from a model defined on a longer time interval conditional on an `MCMCChains.Chain` object that was generated by Bayesian inference.

There was a problem with this approach combined to vectorised random variables, but I've used "fix 1" from the issue I submitted to `Turing` https://github.com/TuringLang/Turing.jl/issues/2239 .

NB: This PR should be strengthened with direct distribution tests on underlying forecast variables using `HypothesisTests.jl`. The reason this is not yet implemented is due to wanting to insert a test environment into the pipeline (this will be an issue).

Closes #231 .

### CODE REVIEW

**Comment by seabbs** [comment]
> NB: This PR should be strengthened with direct distribution tests on underlying forecast variables using HypothesisTests.jl. The reason this is not yet implemented is due to wanting to insert a test environment into the pipeline (this will be an issue)

I suggest we make this a new issue/PR vs being blocked

**Comment by SamuelBrand1** [comment]
> > NB: This PR should be strengthened with direct distribution tests on underlying forecast variables using HypothesisTests.jl. The reason this is not yet implemented is due to wanting to insert a test environment into the pipeline (this will be an issue)
> 
> I suggest we make this a new issue/PR vs being blocked

Added an issue. Agree this is not a blocker.

**Review by seabbs — APPROVED** [review]
LGTM. 

I think we should merge and open new issues to: 

1. Add unit tests based on the new example/toy/test pipeline
2. Work to do to port core functionality into `EpiAware`

I see some seemingly unrelated changes in `define_epiprob`. I don't love the hard coding of the generation time as `Gamma` but as this will shortly need a refactor when we merge in the changes to the infection module in `EpiAware` I think this approach is fine for now.

**Comment by seabbs** [comment]
I forgot to add but f2f @SamuelBrand1 and I have spoken about how great this functionality is in `Turing` - very exciting stuff.

**Comment by SamuelBrand1** [comment]
> I forgot to add but f2f @SamuelBrand1 and I have spoken about how great this functionality is in `Turing` - very exciting stuff.

The `Turing.predict` functionality is really interesting.

**Comment by SamuelBrand1** [comment]
> LGTM.
> 
> I think we should merge and open new issues to:
> 
> 1. Add unit tests based on the new example/toy/test pipeline
> 2. Work to do to port core functionality into `EpiAware` (i.e. the method to extend epiproblems and a helper wrapper like `generate_forecasts` but with less dependence on configs).
> 
> I see some seemingly unrelated changes in `define_epiprob`. I don't love the hard coding of the generation time as `Gamma` but as this will shortly need a refactor when we merge in the changes to the infection module in `EpiAware` I think this approach is fine for now.

Agreed. The hard coded preference of the analysis we are doing is what is keeping this out of `EpiAware` atm.

**Pull request merged**
